### ISSUE TITLE
svg icons shall be svg, not images

### ISSUE THREAD

**Issue by wdavidw** [adaltas/node-pad-docs#1]
All icons I have opened are images and not svg instructions. For example, "icon-light.svg" is `<?xml version="1.0" standalone="no"?><!-- Generator: Gravit.io --><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="isolation:isolate" viewBox="250 915 50.137 14" width="50.137" height="14"><image xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAOCAYAAABth09nAAABoElEQVRIS9VWwW3CQBDc3Yd5hg5CB3EH0EGSDvy5Ez9IB6QC8M9wD5wK4hJMB9BBSoAvDzYadI4MImAMkZyTLEvW7t7M3XpnmO6wjDEDZo6IKPTllkSUi0icJMkXvvX7/c5utxuoasjMvVJctt1u4zRN17dA4VuSjTEA9UlEnTN1JkQEkKMzMWsReU2SJK+LpzYRY0zEzGMiatfd/DhPVYfOubhOvauJ+BYBgZc6G17KUVXcyptzDu1ZebG1duz7NkcR59ziONuD73rwf0LgxO2AUEZEi1Ok0NZE1C3+NxBB/z5Upt7QQPa9Pm8ovqqw3vf/iDEmY+bnqlkNi1vNZrNwTySKonYQBOjJp4aBvARnIyIhtOpnav1DMhtV7RWD4GD8ejKYFJhQTV4rVY3K0+ykjlhrocLDO0wzbDhhZkxG1Lv5gJg5nk6nqHWwfhVE3E6r1RqB+ZWENpj/IpIeWw7oEdRbVaFFj1de+YeIjArvVplIOdBai43xFJ6qfLILVV0z81JVs6qK7H0azCOEDXXxLvRs5f0ZDCdMZX7JVH4DJzuq0zueNP0AAAAASUVORK5CYII=" x="250" y="915" width="50.137" height="14" style=""/></svg>`

**Comment by sergkoudi** [comment]
Done with all the icons.

**Comment by wdavidw** [comment]
Did you update the icon.gvdesign accordingly ?

**Comment by sergkoudi** [comment]
Updated
